### ISSUE TITLE
OpenAPI Spec Generator

### ISSUE THREAD

**Issue by sergiimk** [kamu-data/kamu-node#140]
- [x] Add OpenAPI schema generation to `api-server` (https://github.com/kamu-data/kamu-cli/pull/911)
- [x] Integrate static OpenAPI spec into docs.kamu.dev
- [x] (Optional) Add OpenAPI spec sanity check CI step (https://github.com/kamu-data/kamu-cli/pull/956)

**Comment by sergiimk** [comment]
Done
