### ISSUE TITLE
Integrate Platform With Demo Env

### ISSUE THREAD

**Issue by sergiimk** [kamu-data/kamu-node#15]
## About
Deploy an instance of Kamu Platform alongside the demo environment and incorporate it into the tutorials.

## Product Requirements
- A special instance of Kamu Platform will be deployed for demo purposes
- Instead of raw Minio we will change demo content to guide people to push/pull data to the platform

## Technical Details
See [RFC: Integrating Web Platform with Demo Environment](https://docs.google.com/document/d/1TiK9TUO3hjfJFdo6Ra4_go5km0ab3-rM8zsUjYekeC0/edit)

## Tasks
- [x] Example multi-tenant repo: https://github.com/kamu-data/kamu-node/issues/28
- [x] Repository bootstrap script
  - Related to: https://github.com/kamu-data/kamu-node/issues/43
- [x] Design how demo <> platform auth will work
- [x] Connect JupyterHub with the platform
  - [x] Authentication
    - https://github.com/kamu-data/kamu-cli/pull/519
    - https://github.com/kamu-data/kamu-cli/issues/525
  - [x] Fix smart push / pull via repo https://github.com/kamu-data/kamu-cli/issues/521
  - [x] Search https://github.com/kamu-data/kamu-cli/issues/508
- [x] Rename covid datasets
- [x] Update notebooks
- [x] Keep datasets in demo node up-to-date
- [ ] Functional `docker-compose` demo (postponed as demo is mostly functional and push is low priority)
- [x] Announce on Discord

**Comment by sergiimk** [comment]
Closing as completed
